# Generated by Django 3.2.9 on 2021-12-06 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id_aluno', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(max_length=255)),
                ('ano_nascimento', models.DateField(auto_now_add=True)),
                ('nome_mae', models.CharField(max_length=255)),
                ('nome_pai', models.CharField(max_length=255)),
                ('ano_ingresso', models.DateField(auto_now_add=True)),
                ('turma', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=10)),
            ],
        ),
    ]
