# Generated by Django 3.2.9 on 2021-12-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='ano_ingresso',
            new_name='data_cadastro',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='ano_nascimento',
            field=models.CharField(max_length=255),
        ),
    ]
